sudo cp sipp.call /var/spool/asterisk/outgoing/
sudo cp sipp_1.call /var/spool/asterisk/outgoing/
sudo cp sipp_2.call /var/spool/asterisk/outgoing/
sudo cp sipp_3.call /var/spool/asterisk/outgoing/
sudo cp sipp_4.call /var/spool/asterisk/outgoing/
sudo cp sipp_5.call /var/spool/asterisk/outgoing/
sudo cp sipp_6.call /var/spool/asterisk/outgoing/
sudo cp sipp_7.call /var/spool/asterisk/outgoing/
sudo cp sipp_8.call /var/spool/asterisk/outgoing/
sudo cp sipp_9.call /var/spool/asterisk/outgoing/
